### ISSUE TITLE
Compile ofxCcv on raspberry pi 

### ISSUE THREAD

**Issue by khangprolxag** [kylemcdonald/ofxCcv#12]
Can you make a library for raspberry pi?
because i can't compile it, cause too many errors :(

**Comment by khangprolxag** [comment]
Anyway, i've compiled this addon for raspberry pi. 
this issue can be closed now, thank you

**Comment by genekogan** [comment]
@khangprolxag if you have ofxCcv working for raspberry pi, this would be a very welcome pull request for this repo.

**Comment by khangprolxag** [comment]
yes i will but i still have some error on Rasberry Pi Zero, but work perfectly on Rasberry Pi 2 or 3...

**Comment by genekogan** [comment]
that's fantastic! how fast do the examples run? did you just make a new static library for pi, or did you also have to modify any of ofxCcv's code?  if the first one, then perhaps just PR it to the main repo. if changes to ofxCcv were needed, might be good to make a new branch.

**Comment by khangprolxag** [comment]
i haven't tried example yet but i wrote my code and tested, it worked. i don't have to modify ofxCcv's code, i just base on your tutorial how do you make static library for linux64 and then i tried on my rasberry pi
here this is libccv.a that i have compiled: https://drive.google.com/file/d/0B2csDFRMXb34dWdyTHFCOEVwcW8/view?usp=sharing

Do you have any idea for the "segmentation fault" error ? Openframeworks doesn't show any errors detail else...

**Comment by genekogan** [comment]
Segmentation fault can be caused by many things, but first one I can think of is that the Pi doesn't have enough memory to load the image-net module.

**Comment by genekogan** [comment]
At the moment I don't have a Pi, so I may not be able to test this immediately.

**Comment by khangprolxag** [comment]
i think so, i can turn on public SSH on my raspberry if you would like. I really really need this library gets to work on my raspberry Pi Zero

**Comment by genekogan** [comment]
there may be some interest in this project from @AndreasRef. pinging him here...

**Comment by AndreasRef** [comment]
Thanks, I'm really interested in getting ofxCCV running on Raspberry as well, so any progress @khangprolxag  would like to share would be highly appreciated  :)

**Comment by khangprolxag** [comment]
@AndreasRef  ya i will, do you have raspberry pi? Can you help me to test the library that i've compiled ?
[create a directory like this "ofxCcv/libs/ccv/lib/armv6l" and place libccv.a into]
https://drive.google.com/file/d/0B2csDFRMXb34dWdyTHFCOEVwcW8/view?usp=sharing
Thank you so much.

**Comment by AndreasRef** [comment]
Not currently, but can have a look later this month.

**Comment by barneyElDinosaurio** [comment]
Hey,some advance?, how can i help?, im interested in compile ofxCcv in Rpi Zero. Help me please.

**Comment by khangprolxag** [comment]
Its working on pi zero but the speed is ultra slow. I think you should try
another library

**Comment by quappefeeder** [comment]
> Its working on pi zero but the speed is ultra slow. I think you should try another library

Hi there, have you tried another suitable library so far? I am also trying to use such an addon on my RPi Zero.
