### ISSUE TITLE
compile problems

### ISSUE THREAD

**Issue by antimodular** [kylemcdonald/ofxCcv#2]
looks like an interesting addon. i hope it does things like Deep Belief image recognition framework:
https://github.com/jetpacapp/DeepBeliefSDK

anyway.
i am trying to compile your addon but get these errors:

https://www.dropbox.com/s/fnbw65wt2hf8qr0/Screen%20Shot%202015-02-18%20at%207.51.40%20PM.png?dl=0

i am on OS X 10.10 with of 0.8.4

**Comment by kylemcdonald** [comment]
ahh sorry, i just realized these are new features that will be release with OF 0.9.0.

you can either check out the most recent version of OF from github, or wait for 0.9.0 to be released, or i will get to these errors and make the addon backwards compatible when i get a chance.

**Comment by antimodular** [comment]
i see.
i will just download  OF 0.9.0.
thanks.

**Comment by antimodular** [comment]
got it to work with 32bit version and of_v0.9.0RC1_osx_release.
it thought i was a baboon but did identify my sunglasses correctly.
