### ISSUE TITLE
runtime error on classify

### ISSUE THREAD

**Issue by genekogan** [kylemcdonald/ofxCcv#3]
`classify` leads to this runtime error for me when running the example. the database and .words file are in place, though the generated sqlite is 0 bytes, if that's relevant. same result for both an image and cam. am i missing something? 

<img width="857" alt="screen shot 2015-07-16 at 12 05 26 am" src="https://cloud.githubusercontent.com/assets/1335251/8715365/7dc831aa-2b4e-11e5-9371-e4f8d060324f.png">

**Comment by kylemcdonald** [comment]
my data folder looks like this before i run, is it the same for you?

```
kyle:data kyle$ ls -lh
total 679480
-rw-r--r--  1 kyle  staff   2.3K Jun 24 14:02 classification.png
-rw-r--r--  1 kyle  staff   213M Dec 23  2014 image-net-2012-vgg-d.sqlite3
-rw-r--r--  1 kyle  staff   117M Jan 30 12:06 image-net-2012.sqlite3
-rw-r--r--  1 kyle  staff    21K Jan 30 12:06 image-net-2012.words
-rw-r--r--@ 1 kyle  staff   812K Jan 31 13:43 nature.png
```

**Comment by genekogan** [comment]
ah i see now, my mistake, i was missing image-net-2012-vgg-d.sqlite3 but was attempting to load that instead of image-net-2012.sqlite3. works great now.
