### ISSUE TITLE
linker errors when building from project generator

### ISSUE THREAD

**Issue by genekogan** [kylemcdonald/ofxCcv#5]
when building a project from PG, two issues:

1) i get linker errors when calling `toCcv` anywhere outside of main.  this can be fixed either by making `toCcv` a static function or by breaking out ofCcv.h into a header and cpp and compiling `toCcv` from the cpp file. would probably make sense to go the second route, as is the case for most addons.

2) the binary is not automatically added into the project file from PG -- if i'm not mistaken this can be done via an addon_config.mk.

**Comment by genekogan** [comment]
actually #2 is unnecessary but splitting ofxCcv.h to .h and .cpp gets this to work straight from PG.

**Comment by kylemcdonald** [comment]
from a workshop i just did two days ago no one seemed to have problems regarding point 2 (osx, linux and windows, all 0.9.0).

but if you would like to make the first change that would be great -- otherwise i'll do this next time i work on ofxCcv (probably not within the next month).

**Comment by genekogan** [comment]
this is done as of f1c9efbdcc5155fa5413f054a68b6e59c12c7613
